version: "3.8"

services:
  client:
    build: client/
    ports:
      - 4200:80
    networks:
      - public
      
  server:
    build: server/
    ports:
      - 3000:3000
    environment:
      - DB_USER=jaumoso
      - DB_PASSWORD=7iZuK4Xue9fWHlVh
      - JWT_SECRET=Ey#o.nBTsq32pF%#TGk$@9kecO yd~j#zUa3xB=[
    networks:
      - public
      
networks:
  public:
    driver: bridge
