name: Build Test Run Analyze Containerize Push

on:
  push:
    branches: [ "main" ]

jobs:
  
  build-run-test-client:
       if: ${{github.repository == 'jaumoso/cromoteca'}}
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v2
         - name: install
           run: |
            cd client
            yarn install
         - name: build
           run: |
            cd client
            yarn build
         #- name: test
         #  run: |
         #   cd client
         #   yarn test --no-watch --code-coverage

  build-run-test-server:
       needs: build-run-test-client
       if: ${{github.repository == 'jaumoso/cromoteca'}}
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v2
         - name: install
           run: |
            cd server
            yarn install
         - name: build
           run: |
            cd server
            yarn build
         #- name: test
         #  run: |
         #   cd server
         #   yarn test --watch=false --coverage
            
  sonar-client:
    needs: build-run-test-server
    name: Sonar Analyze ANGULAR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: go to folder
        run: |
          cd client
          pwd
          ls
      - name: SonarCloud Scan
        # You may pin to the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@cb201f3b2d7a38231a8c042dfea4539c8bea180b
        uses: SonarSource/sonarcloud-github-action@master
        with:
          # Additional arguments to the sonarcloud scanner
          args: 
            -Dsonar.projectKey=jaumoso_cromoteca-client
            -Dsonar.organization=jaumoso
          # Set the sonar.projectBaseDir analysis property
          projectBaseDir: client/.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CLIENT }}

  sonar-server:
    needs: sonar-client
    name: Sonar Analyze NESTJS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: go to folder
        run: |
          cd server
          pwd
          ls
      - name: SonarCloud Scan
        # You may pin to the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@cb201f3b2d7a38231a8c042dfea4539c8bea180b
        uses: SonarSource/sonarcloud-github-action@master
        with:
          # Additional arguments to the sonarcloud scanner
          args: 
            -Dsonar.projectKey=jaumoso_cromoteca-server
            -Dsonar.organization=jaumoso
          # Set the sonar.projectBaseDir analysis property
          projectBaseDir: server/.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SERVER }}

  build-docker-image-and-publish:
     needs: sonar-server
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Docker Login
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Build and Publish Docker CLIENT
       id: docker_build_client
       uses: docker/build-push-action@v2
       with:
         context: client/.
         push: true
         tags: |
           ghcr.io/jaumoso/cromoteca/cromoteca-client:latest
     - name: Build and Publish Docker SERVER
       id: docker_build_server
       uses: docker/build-push-action@v2
       with:
         context: server/.
         push: true
         tags: |
           ghcr.io/jaumoso/cromoteca/cromoteca-server:latest
     - name: Print Image Digests
       run: |
         echo ${{ steps.docker_build.outputs.digests }}
