name: Build Test Run Analyze Containerize Push

on:
  push:
    branches: [ "main" ]

jobs:
  sonar-cloud:
    name: Sonar Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        # You may pin to the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@cb201f3b2d7a38231a8c042dfea4539c8bea180b
        uses: SonarSource/sonarcloud-github-action@master
        with:
          # Additional arguments to the sonarcloud scanner
          args: 
            -Dsonar.projectKey=Jaumoso_Cromoteca
            -Dsonar.organization=jaumoso
          # Set the sonar.projectBaseDir analysis property
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  build-run-test-client:
       if: ${{github.repository == 'jaumoso/cromoteca'}}
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v2
         - name: install
           run: |
            cd client
            npm install
         - name: build
           run: |
            cd client
            npm run build
         - name: test
           run: |
            cd client
            npm run test
          
  build-run-test-server:
       if: ${{github.repository == 'jaumoso/cromoteca'}}
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v2
         - name: install
           run: |
            cd server
            npm install
         - name: build
           run: |
            cd server
            npm run build
         - name: test
           run: |
            cd server
            npm run test

  build-docker-image-and-publish:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Docker Login
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Build and Publish Docker CLIENT
       id: docker_build_client
       uses: docker/build-push-action@v2
       with:
         context: client/.
         push: true
         tags: |
           ghcr.io/jaumoso/cromoteca/cromoteca-client:latest
     - name: Build and Publish Docker SERVER
       id: docker_build_server
       uses: docker/build-push-action@v2
       with:
         context: server/.
         push: true
         tags: |
           ghcr.io/jaumoso/cromoteca/cromoteca-server:latest
     - name: Print Image Digests
       run: |
         echo ${{ steps.docker_build.outputs.digests }}
