name: Crear imagenes de Docker y push a Packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

   build-docker-image-and-publish:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Docker Login
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Build and Publish Docker images
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         context: client/.
         push: true
         tags: |
           ghcr.io/jaumoso/cromoteca/cromoteca-client:latest
           
     - name: Print Image Digests
       run: |
         echo ${{ steps.docker_build.outputs.digests }}
