name: Build Test Run Analyze Containerize Push

on:
  push:
    branches: 
      - azure
    paths-ignore:
      - '**/README.md'
jobs:

  build-docker-images-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Publish Docker CLIENT
      id: docker_build_client
      uses: docker/build-push-action@v2
      with:
        context: client/.
        push: true
        tags: |
          ghcr.io/jaumoso/cromoteca/cromoteca-client-azure:${{ github.sha }}
